[tools]
codex = "latest"
dua = "latest"
fzf = "latest"
git-cliff = "latest"
github-cli = "latest"
glab = "latest"
go = "latest"
golangci-lint = "latest"
jq = "latest"
just = "latest"
node = "26"
opencode = "latest"
pipx = "latest"
"pipx:pre-commit" = "latest"
prettier = "latest"
python = "latest"
rg = "latest"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yamlfmt = "latest"
bun = "latest"
rclone = "latest"
"npm:skills" = "latest"
"npm:corepack" = "latest"
"npm:@moonrepo/cli" = "latest"
imagemagick = "latest"
lychee = "latest"

[env]
GOBIN = ""
